[package]
name = "wezlib"
description = "The WESYS zlib wrapper PES puts around compressed files"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
flate2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
