"""Migrate the pre-Fox tracer's old-layout source to the Studio layout by hand, for what
`compile` handles: Players/20 - Fumos/, the team colors, and Kits/g1/ from 4.16.

Writes .tmp/tracer_prefox/studio/jp Midcup Tracer/ (refuses to run when it exists).
"""

import base64
import re
import shutil
from pathlib import Path

HERE = Path(r"C:\Data\4cc\Tools_Mine\4cc-studio\.tmp\tracer_prefox")
# Pre-Fox kits compile from step 4.16: until then a kit refuses the whole export, so the twin
# holds none (the kit's rows are "not produced yet" in the parity test).
WITH_KIT = False
OLD = HERE / "old" / "jp Tracer"
FACE = OLD / "Faces" / "XXX20 - Fumos"
TARGET = HERE / "studio" / "jp Midcup Tracer"
PLAYER = TARGET / "Players" / "20 - Fumos"

# Old packed names to the Studio's source names: a model's `.mtl` is found by a name that
# starts or ends its stem, which `oral_glove_l_win32` would not match.
RENAMED = {
    "face_high_win32.model": "face_high.model",
    "oral_boots_win32.model": "boots.model",
    "oral_glove_l_win32.model": "glove_l.model",
    "oral_glove_r_win32.model": "glove_r.model",
}
# face.xml is generated by the compiler; its <dif> becomes face_diff.bin.
DROPPED = {"face.xml"}

assert not TARGET.exists(), f"{TARGET} exists; remove it by hand first"
names = {path.name for path in FACE.iterdir()}
assert set(RENAMED) <= names and DROPPED <= names, names

PLAYER.mkdir(parents=True)
for path in sorted(FACE.iterdir()):
    if path.name in DROPPED:
        continue
    shutil.copy2(path, PLAYER / RENAMED.get(path.name, path.name))

xml = (FACE / "face.xml").read_bytes().decode("utf-8")
found = re.findall(r"<dif>(.*?)</dif>", xml, flags=re.S)
assert len(found) == 1, found
diff = base64.b64decode("".join(found[0].split()), validate=True)
assert diff[:4] == b"FACE", diff[:4]
(PLAYER / "face_diff.bin").write_bytes(diff)

if WITH_KIT:
    kit = TARGET / "Kits" / "g1"
    kit.mkdir(parents=True)
    shutil.copy2(OLD / "Kit Textures" / "u0XXXg1.dds", kit / "kit.dds")
    # The GK config decoded as PES 17 by `kit_config` (`KitConfig::decode`, then `to_toml`).
    shutil.copy2(HERE / "g1_config.toml", kit / "config.toml")
    # The note's 1st GK entry, "#FFFFFF - #000000".
    (kit / "colors.txt").write_bytes(b"#ffffff\n#000000\n")
# The note's team colors, "058 080 177" and "255 255 255".
(TARGET / "colors.txt").write_bytes(b"#3a50b1\n#ffffff\n")

for path in sorted(TARGET.rglob("*")):
    if path.is_file():
        print(f"{path.stat().st_size:8d}  {path.relative_to(TARGET)}")
