[package]
name = "team_compiler"
description = "The Team compiler: aesthetics exports to CPK archives"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aesthetics_export.workspace = true
anyhow.workspace = true
archives.workspace = true
clap.workspace = true
cpk.workspace = true
egui.workspace = true
fmdl.workspace = true
fpk.workspace = true
ftex.workspace = true
kit_config.workspace = true
pes_version.workspace = true
pipeline.workspace = true
serde.workspace = true
studio_core.workspace = true
teams_list.workspace = true
toml.workspace = true
uniparam.workspace = true
vtree.workspace = true

[dev-dependencies]
crossbeam-channel.workspace = true

[lints]
workspace = true
