//! The per-version schema: declarative field tables (data only) plus the record
//! layouts they describe. A bit offset appears in `schema/pesNN.rs` or nowhere;
//! `codec/` interprets these tables and never carries one itself. The table
//! modules are generated by `scripts/derive_savefile_schema.py` (method:
//! `docs/plans/pes_savefile/codec.md`, "Schema-driven save codec").

/// The version-neutral field vocabularies the tables name.
pub mod fields;
/// The ingame-face run's field table, hand-written (the run is opaque bytes
/// the table names known bits of).
pub mod ingame_face;
/// The per-version advanced-instruction mappings (`decode`/`encode` between a
/// stored value and `model::instruction::Instruction`).
pub mod instruction;
#[cfg(test)]
mod instruction_golden;
/// The per-version caps on the ingame-face type fields.
pub mod limits;
mod pes15;
mod pes16;
mod pes17;
mod pes18;
mod pes19;
mod pes20;
/// The per-version playing-style lists (`decode`/`encode` between a stored
/// index and `model::playstyle::PlayStyle`).
pub mod playstyle;
#[cfg(test)]
mod playstyle_golden;
/// The per-version Texport file layouts (18-21) and payload offsets (15-17).
pub mod texport;

use pes_version::PesVersion;

use fields::{
    PlayerField, PlayerText, PresetField, RosterField, TacticsField, TeamField, TeamText,
};

/// One bit run of a record.
pub struct FieldSpec<F> {
    /// The model field the run decodes to.
    pub field: F,
    /// Bit position from the record's first byte.
    pub bit_offset: u32,
    /// Run length in bits.
    pub bit_width: u32,
}

/// A regular run of indexed fields (`play_skill[0..41]`, roster slots, formation players):
/// element `i` is `make(i)` at `base_bit + i * stride_bits`.
pub struct ArraySpec<F> {
    /// Builds the indexed field variant for element `i`.
    pub make: fn(u8) -> F,
    /// Element count.
    pub count: u8,
    /// Bit position of element 0.
    pub base_bit: u32,
    /// Bits between consecutive elements.
    pub stride_bits: u32,
    /// Bits per element.
    pub bit_width: u32,
}

/// A NUL-terminated byte string field.
pub struct TextSpec<T> {
    /// The model text the bytes decode to.
    pub text: T,
    /// Byte offset from the record's first byte.
    pub byte_offset: u32,
    /// Byte length of the whole field, terminator included.
    pub len: u32,
}

/// A byte run carried verbatim.
pub struct ByteRun {
    /// Byte offset from the record's first byte.
    pub byte_offset: u32,
    /// Byte length.
    pub len: u32,
}

/// One record kind's layout for one version (player, appearance, team, roster).
pub struct RecordSchema<F: 'static, T: 'static> {
    /// Record size in bytes.
    pub size: usize,
    /// The scalar bit runs.
    pub fields: &'static [FieldSpec<F>],
    /// The indexed runs.
    pub arrays: &'static [ArraySpec<F>],
    /// The text fields.
    pub texts: &'static [TextSpec<T>],
    /// The opaque ingame-face run: `Some` on the record that carries the
    /// appearance block (the 15/16 appearance record, the 17+ player record).
    pub ingame_face: Option<ByteRun>,
}

impl<F: PartialEq + Copy, T> RecordSchema<F, T> {
    /// Whether the schema stores `field`: a `fields` row names it or an
    /// `arrays` element's `make(i)` produces it.
    pub fn has(&self, field: F) -> bool {
        self.fields.iter().any(|spec| spec.field == field)
            || self
                .arrays
                .iter()
                .any(|array| (0..array.count).any(|i| (array.make)(i) == field))
    }
}

/// A per-preset setting: one byte at `bit_offset + preset * preset_stride_bits`.
pub struct PresetSpec {
    /// The tactic setting the byte holds.
    pub field: PresetField,
    /// Bit position inside the preset's block.
    pub bit_offset: u32,
}

/// The 3 x 3 formation blocks: player `slot`'s position byte at
/// `base + preset * preset_stride + formation * formation_stride + slot * slot_stride`, its
/// y then x bytes at `.. + y_offset + slot * pair_stride` and `.. + x_offset + ..`.
pub struct FormationLayout {
    /// Bit position of formation 0's first slot within a preset block.
    pub base_bit: u32,
    /// Bits between consecutive formations.
    pub formation_stride_bits: u32,
    /// Bits between consecutive position bytes.
    pub slot_stride_bits: u32,
    /// Bits from the formation's first position byte to the y/x pair block.
    pub y_offset_bits: u32,
    /// Bits from the formation's first position byte to the x byte of each pair.
    pub x_offset_bits: u32,
    /// Bits between consecutive y/x pairs.
    pub pair_stride_bits: u32,
}

/// The advanced instructions (PES 17+): one part at
/// `base + preset * preset_stride + side * side_stride + index * index_stride + part * part_stride`.
pub struct InstructionLayout {
    /// Bit position of the first instruction's first part within a preset block.
    pub base_bit: u32,
    /// Bits between the attacking and defending instructions.
    pub side_stride_bits: u32,
    /// Bits between the two instructions of a side.
    pub index_stride_bits: u32,
    /// Bits between an instruction's id and its player id.
    pub part_stride_bits: u32,
}

/// The tactics record: the scalar and array fields plus the three regular nested blocks,
/// which the derivation checks are regular before emitting them this way.
pub struct TacticsSchema {
    /// Record size in bytes.
    pub size: usize,
    /// The scalar bit runs.
    pub fields: &'static [FieldSpec<TacticsField>],
    /// The indexed runs.
    pub arrays: &'static [ArraySpec<TacticsField>],
    /// Bits between consecutive preset blocks.
    pub preset_stride_bits: u32,
    /// The per-preset settings.
    pub presets: &'static [PresetSpec],
    /// The formation block layout.
    pub formations: FormationLayout,
    /// The advanced-instruction block layout; `None` on PES 15/16.
    pub instructions: Option<InstructionLayout>,
}

impl TacticsSchema {
    /// Whether the tactics record stores `field` (scalar fields and arrays, as
    /// `RecordSchema::has`; preset settings via [`Self::has_preset`],
    /// formations always, instructions when `instructions` is `Some`).
    pub fn has(&self, field: TacticsField) -> bool {
        if let TacticsField::Preset { field, .. } = field {
            return self.has_preset(field);
        }
        if let TacticsField::Formation { .. } = field {
            return true;
        }
        if let TacticsField::Instruction { .. } = field {
            return self.instructions.is_some();
        }
        self.fields.iter().any(|spec| spec.field == field)
            || self
                .arrays
                .iter()
                .any(|array| (0..array.count).any(|i| (array.make)(i) == field))
    }

    /// Whether each preset block stores `field`.
    pub fn has_preset(&self, field: PresetField) -> bool {
        self.presets.iter().any(|spec| spec.field == field)
    }
}

/// Where a section of records sits in the payload.
pub struct SectionLayout {
    /// Byte offset of the first record.
    pub offset: usize,
    /// Byte offset of the little-endian u16 record count.
    pub count_offset: usize,
}

/// Every section's layout for one game version.
pub struct VersionSchema {
    /// The version these tables describe.
    pub version: PesVersion,
    /// The player record section.
    pub players: SectionLayout,
    /// The player record layout.
    pub player: &'static RecordSchema<PlayerField, PlayerText>,
    /// PES 15/16: the separate appearance array (keyed by player id at +0); `None` when the
    /// appearance fields are inside the player record.
    pub appearance: Option<(
        SectionLayout,
        &'static RecordSchema<PlayerField, PlayerText>,
    )>,
    /// The team record section.
    pub teams: SectionLayout,
    /// The team record layout.
    pub team: &'static RecordSchema<TeamField, TeamText>,
    /// The roster record section.
    pub rosters: SectionLayout,
    /// The roster record layout.
    pub roster: &'static RecordSchema<RosterField, TeamText>,
    /// The tactics record section.
    pub tactics: SectionLayout,
    /// The tactics record layout.
    pub tactic: &'static TacticsSchema,
}

/// The field tables of one game version. PES 20 and 21 share one player table;
/// PES 21's team record carries its own layout.
pub fn schema_for(version: PesVersion) -> &'static VersionSchema {
    match version {
        PesVersion::Pes15 => &pes15::PES15,
        PesVersion::Pes16 => &pes16::PES16,
        PesVersion::Pes17 => &pes17::PES17,
        PesVersion::Pes18 => &pes18::PES18,
        PesVersion::Pes19 => &pes19::PES19,
        PesVersion::Pes20 => &pes20::PES20,
        PesVersion::Pes21 => &pes20::PES21,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every bit run and text field of a record schema as half-open bit ranges.
    fn record_runs<F: Copy, T>(schema: &RecordSchema<F, T>) -> Vec<(u32, u32)> {
        let mut runs: Vec<(u32, u32)> = schema
            .fields
            .iter()
            .map(|f| (f.bit_offset, f.bit_offset + f.bit_width))
            .collect();
        for a in schema.arrays {
            for i in 0..u32::from(a.count) {
                let start = a.base_bit + i * a.stride_bits;
                runs.push((start, start + a.bit_width));
            }
        }
        for t in schema.texts {
            runs.push((t.byte_offset * 8, t.byte_offset * 8 + t.len * 8));
        }
        if let Some(run) = &schema.ingame_face {
            runs.push((run.byte_offset * 8, (run.byte_offset + run.len) * 8));
        }
        runs
    }

    /// The tactics record's runs, presets, formations and instructions expanded.
    fn tactics_runs(schema: &TacticsSchema) -> Vec<(u32, u32)> {
        let mut runs: Vec<(u32, u32)> = schema
            .fields
            .iter()
            .map(|f| (f.bit_offset, f.bit_offset + f.bit_width))
            .collect();
        for a in schema.arrays {
            for i in 0..u32::from(a.count) {
                let start = a.base_bit + i * a.stride_bits;
                runs.push((start, start + a.bit_width));
            }
        }
        for preset in 0..3u32 {
            let preset_base = preset * schema.preset_stride_bits;
            for p in schema.presets {
                let start = preset_base + p.bit_offset;
                runs.push((start, start + 8));
            }
            let f = &schema.formations;
            for formation in 0..3u32 {
                let base = preset_base + f.base_bit + formation * f.formation_stride_bits;
                for slot in 0..11u32 {
                    runs.push((
                        base + slot * f.slot_stride_bits,
                        base + slot * f.slot_stride_bits + 8,
                    ));
                    runs.push((
                        base + f.y_offset_bits + slot * f.pair_stride_bits,
                        base + f.y_offset_bits + slot * f.pair_stride_bits + 8,
                    ));
                    runs.push((
                        base + f.x_offset_bits + slot * f.pair_stride_bits,
                        base + f.x_offset_bits + slot * f.pair_stride_bits + 8,
                    ));
                }
            }
            if let Some(ins) = &schema.instructions {
                for side in 0..2u32 {
                    for index in 0..2u32 {
                        for part in 0..2u32 {
                            let start = preset_base
                                + ins.base_bit
                                + side * ins.side_stride_bits
                                + index * ins.index_stride_bits
                                + part * ins.part_stride_bits;
                            runs.push((start, start + ins.part_stride_bits));
                        }
                    }
                }
            }
        }
        runs
    }

    /// Asserts the half-open bit ranges do not overlap and lie inside `size` bytes.
    fn check_runs(runs: &mut [(u32, u32)], size: usize, what: &str) {
        runs.sort_unstable();
        for pair in runs.windows(2) {
            assert!(pair[0].1 <= pair[1].0, "{what}: runs {pair:?} overlap");
        }
        for &(start, end) in runs.iter() {
            assert!(
                end <= (size * 8) as u32,
                "{what}: run {start}..{end} past the record"
            );
        }
    }

    #[test]
    fn no_two_bit_runs_overlap_and_everything_is_inside_the_record() {
        for version in PesVersion::ALL {
            let schema = schema_for(version);
            check_runs(
                &mut record_runs(schema.player),
                schema.player.size,
                "player",
            );
            if let Some((_, appearance)) = &schema.appearance {
                check_runs(&mut record_runs(*appearance), appearance.size, "appearance");
            }
            check_runs(&mut record_runs(schema.team), schema.team.size, "team");
            check_runs(
                &mut record_runs(schema.roster),
                schema.roster.size,
                "roster",
            );
            check_runs(
                &mut tactics_runs(schema.tactic),
                schema.tactic.size,
                "tactic",
            );
        }
    }

    #[test]
    fn record_sizes_match_the_measured_layout() {
        let players = [112, 112, 188, 188, 188, 312, 312];
        let appearance = [Some(68), Some(72), None, None, None, None, None];
        let teams = [456, 456, 480, 480, 416, 528, 588];
        let rosters = [164, 164, 164, 164, 244, 284, 284];
        let tactics = [516, 520, 628, 628, 628, 628, 628];
        for (i, version) in PesVersion::ALL.iter().enumerate() {
            let schema = schema_for(*version);
            assert_eq!(schema.player.size, players[i], "{version:?} player");
            assert_eq!(
                schema.appearance.as_ref().map(|(_, a)| a.size),
                appearance[i],
                "{version:?} appearance"
            );
            assert_eq!(schema.team.size, teams[i], "{version:?} team");
            assert_eq!(schema.roster.size, rosters[i], "{version:?} roster");
            assert_eq!(schema.tactic.size, tactics[i], "{version:?} tactic");
        }
    }
}
