//! The PES 15 field tables, derived mechanically from the reference PES 15 read walks
//! (method and checks: `docs/plans/pes_savefile/codec.md`, "Schema-driven save codec"). Generated by
//! `scripts/derive_savefile_schema.py`; do not edit by hand.

use pes_version::PesVersion;

use super::fields::{
    PlayerField, PlayerText, PresetField, RosterField, TacticsField, TeamField, TeamText,
};
use super::{
    ArraySpec, FieldSpec, FormationLayout, PresetSpec, RecordSchema, SectionLayout, TacticsSchema,
    TextSpec, VersionSchema,
};

/// The PES 15 player record.
pub(crate) static PLAYER: RecordSchema<PlayerField, PlayerText> = RecordSchema {
    size: 112,
    fields: &[
        FieldSpec {
            field: PlayerField::Id,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: PlayerField::Nationality,
            bit_offset: 80,
            bit_width: 16,
        },
        FieldSpec {
            field: PlayerField::Height,
            bit_offset: 96,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::Weight,
            bit_offset: 104,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::GoalCelebration1,
            bit_offset: 112,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::GoalCelebration2,
            bit_offset: 120,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::AttackingProwess,
            bit_offset: 128,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::DefensiveProwess,
            bit_offset: 135,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Goalkeeping,
            bit_offset: 142,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::FreeKickMotion,
            bit_offset: 156,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::BallControl,
            bit_offset: 160,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Finishing,
            bit_offset: 167,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::LowPass,
            bit_offset: 174,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::LoftedPass,
            bit_offset: 181,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::WeakFootAccuracy,
            bit_offset: 188,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::EditedPlayer,
            bit_offset: 191,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::PlaceKicking,
            bit_offset: 192,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Swerve,
            bit_offset: 199,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Catching,
            bit_offset: 206,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Speed,
            bit_offset: 213,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Form,
            bit_offset: 220,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::ExplosivePower,
            bit_offset: 224,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Jump,
            bit_offset: 231,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Stamina,
            bit_offset: 238,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Age,
            bit_offset: 245,
            bit_width: 6,
        },
        FieldSpec {
            field: PlayerField::RegisteredPosition,
            bit_offset: 251,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::PlayingStyle,
            bit_offset: 256,
            bit_width: 5,
        },
        FieldSpec {
            field: PlayerField::Dribbling,
            bit_offset: 261,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Heading,
            bit_offset: 268,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::BodyControl,
            bit_offset: 275,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::InjuryResistance,
            bit_offset: 282,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::ArmMovementDribbling,
            bit_offset: 285,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::ArmMovementRunning,
            bit_offset: 288,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::CornerKickMotion,
            bit_offset: 291,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::WeakFootUsage,
            bit_offset: 294,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::HunchingDribbling,
            bit_offset: 322,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::HunchingRunning,
            bit_offset: 324,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PenaltyKickMotion,
            bit_offset: 326,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::BallWinning,
            bit_offset: 328,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::KickingPower,
            bit_offset: 335,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::BaseCopy,
            bit_offset: 346,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedBasicSettings,
            bit_offset: 347,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::StrongerFoot,
            bit_offset: 354,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(0),
            bit_offset: 362,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(1),
            bit_offset: 363,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(2),
            bit_offset: 364,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(3),
            bit_offset: 365,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(4),
            bit_offset: 366,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(5),
            bit_offset: 367,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(7),
            bit_offset: 368,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(8),
            bit_offset: 369,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(9),
            bit_offset: 370,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(11),
            bit_offset: 371,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(12),
            bit_offset: 372,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(13),
            bit_offset: 373,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(14),
            bit_offset: 374,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(15),
            bit_offset: 375,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(18),
            bit_offset: 376,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(19),
            bit_offset: 377,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(20),
            bit_offset: 378,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(22),
            bit_offset: 379,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(23),
            bit_offset: 380,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(25),
            bit_offset: 381,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(26),
            bit_offset: 382,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(27),
            bit_offset: 383,
            bit_width: 1,
        },
    ],
    arrays: &[
        ArraySpec {
            make: PlayerField::PlayablePosition,
            count: 13,
            base_bit: 296,
            stride_bits: 2,
            bit_width: 2,
        },
        ArraySpec {
            make: PlayerField::ComStyle,
            count: 7,
            base_bit: 355,
            stride_bits: 1,
            bit_width: 1,
        },
    ],
    texts: &[
        TextSpec {
            text: PlayerText::Name,
            byte_offset: 48,
            len: 46,
        },
        TextSpec {
            text: PlayerText::ShirtName,
            byte_offset: 94,
            len: 18,
        },
    ],
};

/// The PES 15 appearance record; the player id at +0 keys it to its player record.
pub(crate) static APPEARANCE: RecordSchema<PlayerField, PlayerText> = RecordSchema {
    size: 68,
    fields: &[
        FieldSpec {
            field: PlayerField::Id,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: PlayerField::EditedFace,
            bit_offset: 32,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedHair,
            bit_offset: 33,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedPhysique,
            bit_offset: 34,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedStrip,
            bit_offset: 35,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::BootsId,
            bit_offset: 36,
            bit_width: 14,
        },
        FieldSpec {
            field: PlayerField::GlovesId,
            bit_offset: 50,
            bit_width: 14,
        },
        FieldSpec {
            field: PlayerField::BaseCopyId,
            bit_offset: 64,
            bit_width: 32,
        },
        FieldSpec {
            field: PlayerField::NeckLength,
            bit_offset: 96,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::NeckSize,
            bit_offset: 100,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ShoulderHeight,
            bit_offset: 104,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ShoulderWidth,
            bit_offset: 108,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Chest,
            bit_offset: 112,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Waist,
            bit_offset: 116,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ArmSize,
            bit_offset: 120,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ArmLength,
            bit_offset: 124,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Thigh,
            bit_offset: 128,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Calf,
            bit_offset: 132,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::LegLength,
            bit_offset: 136,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::HeadLength,
            bit_offset: 140,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::HeadWidth,
            bit_offset: 144,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::HeadDepth,
            bit_offset: 148,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::WristTapeColorLeft,
            bit_offset: 152,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::WristTapeColorRight,
            bit_offset: 155,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::WristTaping,
            bit_offset: 158,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::SpectaclesColor,
            bit_offset: 160,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::SpectaclesStyle,
            bit_offset: 163,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::Sleeves,
            bit_offset: 166,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Inners,
            bit_offset: 168,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Socks,
            bit_offset: 170,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Undershorts,
            bit_offset: 172,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Untucked,
            bit_offset: 174,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::AnkleTaping,
            bit_offset: 175,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::PlayerGloves,
            bit_offset: 176,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::PlayerGlovesColor,
            bit_offset: 177,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::SkinColor,
            bit_offset: 360,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::IrisColor,
            bit_offset: 512,
            bit_width: 4,
        },
    ],
    arrays: &[],
    texts: &[],
};

/// The PES 15 team record.
pub(crate) static TEAM: RecordSchema<TeamField, TeamText> = RecordSchema {
    size: 456,
    fields: &[
        FieldSpec {
            field: TeamField::Id,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: TeamField::EditedName,
            bit_offset: 144,
            bit_width: 1,
        },
        FieldSpec {
            field: TeamField::EditedShortName,
            bit_offset: 145,
            bit_width: 1,
        },
    ],
    arrays: &[],
    texts: &[
        TextSpec {
            text: TeamText::Name,
            byte_offset: 148,
            len: 70,
        },
        TextSpec {
            text: TeamText::ShortName,
            byte_offset: 218,
            len: 4,
        },
    ],
};

/// The PES 15 roster record.
pub(crate) static ROSTER: RecordSchema<RosterField, TeamText> = RecordSchema {
    size: 164,
    fields: &[FieldSpec {
        field: RosterField::TeamId,
        bit_offset: 0,
        bit_width: 32,
    }],
    arrays: &[
        ArraySpec {
            make: RosterField::Player,
            count: 32,
            base_bit: 32,
            stride_bits: 32,
            bit_width: 32,
        },
        ArraySpec {
            make: RosterField::Number,
            count: 32,
            base_bit: 1056,
            stride_bits: 8,
            bit_width: 8,
        },
    ],
    texts: &[],
};

/// The PES 15 tactics record.
pub(crate) static TACTICS: TacticsSchema = TacticsSchema {
    size: 516,
    fields: &[
        FieldSpec {
            field: TacticsField::TeamId,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: TacticsField::FreeKickTakerLong,
            bit_offset: 4000,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::FreeKickTakerShort,
            bit_offset: 4008,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::FreeKickTakerSecond,
            bit_offset: 4016,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::CornerTakerLeft,
            bit_offset: 4024,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::CornerTakerRight,
            bit_offset: 4032,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::PenaltyTaker,
            bit_offset: 4040,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::Captain,
            bit_offset: 4048,
            bit_width: 8,
        },
    ],
    arrays: &[
        ArraySpec {
            make: TacticsField::Starting,
            count: 11,
            base_bit: 2976,
            stride_bits: 32,
            bit_width: 32,
        },
        ArraySpec {
            make: TacticsField::Bench,
            count: 21,
            base_bit: 3328,
            stride_bits: 32,
            bit_width: 32,
        },
        ArraySpec {
            make: TacticsField::PlayerToJoinAttack,
            count: 3,
            base_bit: 4056,
            stride_bits: 8,
            bit_width: 8,
        },
    ],
    preset_stride_bits: 976,
    presets: &[
        PresetSpec {
            field: PresetField::AttackingStyle,
            bit_offset: 824,
        },
        PresetSpec {
            field: PresetField::Buildup,
            bit_offset: 832,
        },
        PresetSpec {
            field: PresetField::AttackingZone,
            bit_offset: 840,
        },
        PresetSpec {
            field: PresetField::Positioning,
            bit_offset: 848,
        },
        PresetSpec {
            field: PresetField::DefensiveStyle,
            bit_offset: 856,
        },
        PresetSpec {
            field: PresetField::ContainmentArea,
            bit_offset: 864,
        },
        PresetSpec {
            field: PresetField::Pressure,
            bit_offset: 872,
        },
        PresetSpec {
            field: PresetField::SupportRange,
            bit_offset: 880,
        },
        PresetSpec {
            field: PresetField::DefensiveLine,
            bit_offset: 896,
        },
        PresetSpec {
            field: PresetField::Compactness,
            bit_offset: 904,
        },
        PresetSpec {
            field: PresetField::NumbersInAttack,
            bit_offset: 888,
        },
        PresetSpec {
            field: PresetField::NumbersInDefence,
            bit_offset: 912,
        },
    ],
    formations: FormationLayout {
        base_bit: 32,
        formation_stride_bits: 264,
        slot_stride_bits: 8,
        y_offset_bits: 88,
        x_offset_bits: 96,
        pair_stride_bits: 16,
    },
    instructions: None,
};

/// Where every section sits in the Pes 15 payload.
pub(crate) static PES15: VersionSchema = VersionSchema {
    version: PesVersion::Pes15,
    players: SectionLayout {
        offset: 0x4c,
        count_offset: 0x34,
    },
    player: &PLAYER,
    appearance: Some((
        SectionLayout {
            offset: 0x2ab9cc,
            count_offset: 0x36,
        },
        &APPEARANCE,
    )),
    teams: SectionLayout {
        offset: 0x44aa6c,
        count_offset: 0x38,
    },
    team: &TEAM,
    rosters: SectionLayout {
        offset: 0x4e45cc,
        count_offset: 0x38,
    },
    roster: &ROSTER,
    tactics: SectionLayout {
        offset: 0x507194,
        count_offset: 0x38,
    },
    tactic: &TACTICS,
};
