//! The PES 20 and 21 field tables, derived mechanically from the reference PES 20 and 21 read walks
//! (method and checks: `docs/plans/pes_savefile/codec.md`, "Schema-driven save codec"). Generated by
//! `scripts/derive_savefile_schema.py`; do not edit by hand.

use pes_version::PesVersion;

use super::fields::{
    PlayerField, PlayerText, PresetField, RosterField, TacticsField, TeamField, TeamText,
};
use super::{
    ArraySpec, FieldSpec, FormationLayout, InstructionLayout, PresetSpec, RecordSchema,
    SectionLayout, TacticsSchema, TextSpec, VersionSchema,
};

/// The PES 20 and 21 player record.
pub(crate) static PLAYER: RecordSchema<PlayerField, PlayerText> = RecordSchema {
    size: 312,
    fields: &[
        FieldSpec {
            field: PlayerField::Id,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: PlayerField::Nationality,
            bit_offset: 64,
            bit_width: 16,
        },
        FieldSpec {
            field: PlayerField::Height,
            bit_offset: 80,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::Weight,
            bit_offset: 88,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::GoalCelebration1,
            bit_offset: 96,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::GoalCelebration2,
            bit_offset: 104,
            bit_width: 8,
        },
        FieldSpec {
            field: PlayerField::AttackingProwess,
            bit_offset: 112,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::BallControl,
            bit_offset: 119,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::WeakFootUsage,
            bit_offset: 126,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::TightPossession,
            bit_offset: 128,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::LowPass,
            bit_offset: 135,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::LoftedPass,
            bit_offset: 142,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Finishing,
            bit_offset: 149,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::ArmMovementDribbling,
            bit_offset: 156,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::PlaceKicking,
            bit_offset: 160,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Swerve,
            bit_offset: 167,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Speed,
            bit_offset: 174,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::ExplosivePower,
            bit_offset: 181,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::ArmMovementRunning,
            bit_offset: 188,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Jump,
            bit_offset: 192,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::PhysicalContact,
            bit_offset: 199,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::BodyControl,
            bit_offset: 206,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Stamina,
            bit_offset: 213,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::CornerKickMotion,
            bit_offset: 220,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::BallWinning,
            bit_offset: 224,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Aggression,
            bit_offset: 231,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Goalkeeping,
            bit_offset: 238,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Catching,
            bit_offset: 245,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Form,
            bit_offset: 252,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::EditedPlayer,
            bit_offset: 255,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Coverage,
            bit_offset: 256,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Age,
            bit_offset: 263,
            bit_width: 6,
        },
        FieldSpec {
            field: PlayerField::RegisteredPosition,
            bit_offset: 269,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::PlayingStyle,
            bit_offset: 274,
            bit_width: 5,
        },
        FieldSpec {
            field: PlayerField::FreeKickMotion,
            bit_offset: 279,
            bit_width: 5,
        },
        FieldSpec {
            field: PlayerField::Star,
            bit_offset: 284,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::EditedBasicSettings,
            bit_offset: 287,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::DefensiveProwess,
            bit_offset: 288,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Clearing,
            bit_offset: 295,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::Heading,
            bit_offset: 302,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::HunchingDribbling,
            bit_offset: 309,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::HunchingRunning,
            bit_offset: 312,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::PenaltyKickMotion,
            bit_offset: 315,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::WeakFootAccuracy,
            bit_offset: 318,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Dribbling,
            bit_offset: 320,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::InjuryResistance,
            bit_offset: 327,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayingAttitude,
            bit_offset: 329,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::DribblingMotion,
            bit_offset: 331,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::EditedRegisteredPosition,
            bit_offset: 351,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Reflexes,
            bit_offset: 358,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::KickingPower,
            bit_offset: 365,
            bit_width: 7,
        },
        FieldSpec {
            field: PlayerField::EditedPlayablePositions,
            bit_offset: 374,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedAbilities,
            bit_offset: 375,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedSkills,
            bit_offset: 376,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedPlayingStyle,
            bit_offset: 377,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedComStyles,
            bit_offset: 378,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedMotion,
            bit_offset: 379,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::StrongerFoot,
            bit_offset: 381,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::StrongerHand,
            bit_offset: 382,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedFace,
            bit_offset: 1952,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedHair,
            bit_offset: 1953,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedPhysique,
            bit_offset: 1954,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::EditedStrip,
            bit_offset: 1955,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::BootsId,
            bit_offset: 1956,
            bit_width: 14,
        },
        FieldSpec {
            field: PlayerField::GlovesId,
            bit_offset: 1970,
            bit_width: 14,
        },
        FieldSpec {
            field: PlayerField::BaseCopyId,
            bit_offset: 1984,
            bit_width: 32,
        },
        FieldSpec {
            field: PlayerField::NeckLength,
            bit_offset: 2016,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::NeckSize,
            bit_offset: 2020,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ShoulderHeight,
            bit_offset: 2024,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ShoulderWidth,
            bit_offset: 2028,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Chest,
            bit_offset: 2032,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Waist,
            bit_offset: 2036,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ArmSize,
            bit_offset: 2040,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::ArmLength,
            bit_offset: 2044,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Thigh,
            bit_offset: 2048,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::Calf,
            bit_offset: 2052,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::LegLength,
            bit_offset: 2056,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::HeadLength,
            bit_offset: 2060,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::HeadWidth,
            bit_offset: 2064,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::HeadDepth,
            bit_offset: 2068,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::WristTapeColorLeft,
            bit_offset: 2072,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::WristTapeColorRight,
            bit_offset: 2075,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::WristTaping,
            bit_offset: 2078,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::SpectaclesColor,
            bit_offset: 2080,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::SpectaclesStyle,
            bit_offset: 2083,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::Sleeves,
            bit_offset: 2086,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Inners,
            bit_offset: 2088,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Socks,
            bit_offset: 2090,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Undershorts,
            bit_offset: 2092,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Untucked,
            bit_offset: 2094,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::AnkleTaping,
            bit_offset: 2095,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::PlayerGloves,
            bit_offset: 2096,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::PlayerGlovesColor,
            bit_offset: 2097,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::SkinColor,
            bit_offset: 2280,
            bit_width: 3,
        },
        FieldSpec {
            field: PlayerField::IrisColor,
            bit_offset: 2432,
            bit_width: 4,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(0),
            bit_offset: 356,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(1),
            bit_offset: 354,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(2),
            bit_offset: 372,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(3),
            bit_offset: 352,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(4),
            bit_offset: 349,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(5),
            bit_offset: 341,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(6),
            bit_offset: 343,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(7),
            bit_offset: 345,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(8),
            bit_offset: 347,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(9),
            bit_offset: 335,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(10),
            bit_offset: 337,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(11),
            bit_offset: 339,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::PlayablePosition(12),
            bit_offset: 333,
            bit_width: 2,
        },
        FieldSpec {
            field: PlayerField::Skill(0),
            bit_offset: 390,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(1),
            bit_offset: 392,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(2),
            bit_offset: 393,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(3),
            bit_offset: 394,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(4),
            bit_offset: 396,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(5),
            bit_offset: 397,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(6),
            bit_offset: 399,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(7),
            bit_offset: 400,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(8),
            bit_offset: 403,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(9),
            bit_offset: 406,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(10),
            bit_offset: 407,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(11),
            bit_offset: 408,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(12),
            bit_offset: 409,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(13),
            bit_offset: 411,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(14),
            bit_offset: 412,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(15),
            bit_offset: 413,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(16),
            bit_offset: 414,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(17),
            bit_offset: 416,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(18),
            bit_offset: 417,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(19),
            bit_offset: 419,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(20),
            bit_offset: 420,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(21),
            bit_offset: 423,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(22),
            bit_offset: 424,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(23),
            bit_offset: 425,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(24),
            bit_offset: 427,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(25),
            bit_offset: 428,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(26),
            bit_offset: 429,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(27),
            bit_offset: 430,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(28),
            bit_offset: 391,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(29),
            bit_offset: 395,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(30),
            bit_offset: 398,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(31),
            bit_offset: 401,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(32),
            bit_offset: 404,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(33),
            bit_offset: 405,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(34),
            bit_offset: 415,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(35),
            bit_offset: 418,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(36),
            bit_offset: 421,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(37),
            bit_offset: 422,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(38),
            bit_offset: 426,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(39),
            bit_offset: 402,
            bit_width: 1,
        },
        FieldSpec {
            field: PlayerField::Skill(40),
            bit_offset: 410,
            bit_width: 1,
        },
    ],
    arrays: &[ArraySpec {
        make: PlayerField::ComStyle,
        count: 7,
        base_bit: 383,
        stride_bits: 1,
        bit_width: 1,
    }],
    texts: &[
        TextSpec {
            text: PlayerText::Name,
            byte_offset: 54,
            len: 61,
        },
        TextSpec {
            text: PlayerText::ShirtName,
            byte_offset: 115,
            len: 61,
        },
    ],
};

/// The PES 20 team record.
pub(crate) static TEAM: RecordSchema<TeamField, TeamText> = RecordSchema {
    size: 528,
    fields: &[
        FieldSpec {
            field: TeamField::Id,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: TeamField::ManagerId,
            bit_offset: 32,
            bit_width: 32,
        },
        FieldSpec {
            field: TeamField::StadiumId,
            bit_offset: 80,
            bit_width: 16,
        },
        FieldSpec {
            field: TeamField::Color1Red,
            bit_offset: 178,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::Color1Green,
            bit_offset: 184,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::EditedName,
            bit_offset: 190,
            bit_width: 1,
        },
        FieldSpec {
            field: TeamField::Color2Green,
            bit_offset: 192,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::Color2Blue,
            bit_offset: 198,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::EditedStadium,
            bit_offset: 222,
            bit_width: 1,
        },
        FieldSpec {
            field: TeamField::Color1Blue,
            bit_offset: 240,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::Color2Red,
            bit_offset: 246,
            bit_width: 6,
        },
    ],
    arrays: &[],
    texts: &[
        TextSpec {
            text: TeamText::Name,
            byte_offset: 104,
            len: 70,
        },
        TextSpec {
            text: TeamText::ShortName,
            byte_offset: 174,
            len: 4,
        },
    ],
};

/// The PES 21 team record.
pub(crate) static TEAM_21: RecordSchema<TeamField, TeamText> = RecordSchema {
    size: 588,
    fields: &[
        FieldSpec {
            field: TeamField::Id,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: TeamField::ManagerId,
            bit_offset: 32,
            bit_width: 32,
        },
        FieldSpec {
            field: TeamField::StadiumId,
            bit_offset: 80,
            bit_width: 16,
        },
        FieldSpec {
            field: TeamField::Color1Red,
            bit_offset: 178,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::Color1Green,
            bit_offset: 184,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::EditedName,
            bit_offset: 190,
            bit_width: 1,
        },
        FieldSpec {
            field: TeamField::Color2Green,
            bit_offset: 192,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::Color2Blue,
            bit_offset: 198,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::EditedStadium,
            bit_offset: 222,
            bit_width: 1,
        },
        FieldSpec {
            field: TeamField::Color1Blue,
            bit_offset: 240,
            bit_width: 6,
        },
        FieldSpec {
            field: TeamField::Color2Red,
            bit_offset: 246,
            bit_width: 6,
        },
    ],
    arrays: &[],
    texts: &[
        TextSpec {
            text: TeamText::Name,
            byte_offset: 104,
            len: 70,
        },
        TextSpec {
            text: TeamText::ShortName,
            byte_offset: 174,
            len: 4,
        },
    ],
};

/// The PES 20 and 21 roster record.
pub(crate) static ROSTER: RecordSchema<RosterField, TeamText> = RecordSchema {
    size: 284,
    fields: &[FieldSpec {
        field: RosterField::TeamId,
        bit_offset: 0,
        bit_width: 32,
    }],
    arrays: &[
        ArraySpec {
            make: RosterField::Player,
            count: 40,
            base_bit: 32,
            stride_bits: 32,
            bit_width: 32,
        },
        ArraySpec {
            make: RosterField::Number,
            count: 40,
            base_bit: 1312,
            stride_bits: 16,
            bit_width: 16,
        },
    ],
    texts: &[],
};

/// The PES 20 and 21 tactics record.
pub(crate) static TACTICS: TacticsSchema = TacticsSchema {
    size: 628,
    fields: &[
        FieldSpec {
            field: TacticsField::TeamId,
            bit_offset: 0,
            bit_width: 32,
        },
        FieldSpec {
            field: TacticsField::FreeKickTakerLong,
            bit_offset: 4192,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::FreeKickTakerShort,
            bit_offset: 4200,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::FreeKickTakerSecond,
            bit_offset: 4208,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::CornerTakerLeft,
            bit_offset: 4216,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::CornerTakerRight,
            bit_offset: 4224,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::PenaltyTaker,
            bit_offset: 4232,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::Captain,
            bit_offset: 4264,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::AutoSubstitution,
            bit_offset: 4272,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::AutoOffsideTrap,
            bit_offset: 4280,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::AutoPresetChange,
            bit_offset: 4288,
            bit_width: 8,
        },
        FieldSpec {
            field: TacticsField::AutoAttackDefenceLevels,
            bit_offset: 4304,
            bit_width: 8,
        },
    ],
    arrays: &[
        ArraySpec {
            make: TacticsField::Starting,
            count: 11,
            base_bit: 3872,
            stride_bits: 8,
            bit_width: 8,
        },
        ArraySpec {
            make: TacticsField::Bench,
            count: 21,
            base_bit: 3960,
            stride_bits: 8,
            bit_width: 8,
        },
        ArraySpec {
            make: TacticsField::PlayerToJoinAttack,
            count: 3,
            base_bit: 4240,
            stride_bits: 8,
            bit_width: 8,
        },
    ],
    preset_stride_bits: 1280,
    presets: &[
        PresetSpec {
            field: PresetField::AttackingStyle,
            bit_offset: 824,
        },
        PresetSpec {
            field: PresetField::Buildup,
            bit_offset: 832,
        },
        PresetSpec {
            field: PresetField::AttackingZone,
            bit_offset: 840,
        },
        PresetSpec {
            field: PresetField::Positioning,
            bit_offset: 848,
        },
        PresetSpec {
            field: PresetField::DefensiveStyle,
            bit_offset: 856,
        },
        PresetSpec {
            field: PresetField::ContainmentArea,
            bit_offset: 864,
        },
        PresetSpec {
            field: PresetField::Pressure,
            bit_offset: 872,
        },
        PresetSpec {
            field: PresetField::FluidFormation,
            bit_offset: 1280,
        },
        PresetSpec {
            field: PresetField::SupportRange,
            bit_offset: 1152,
        },
        PresetSpec {
            field: PresetField::DefensiveLine,
            bit_offset: 1168,
        },
        PresetSpec {
            field: PresetField::Compactness,
            bit_offset: 1176,
        },
        PresetSpec {
            field: PresetField::NumbersInAttack,
            bit_offset: 1160,
        },
        PresetSpec {
            field: PresetField::NumbersInDefence,
            bit_offset: 1184,
        },
    ],
    formations: FormationLayout {
        base_bit: 32,
        formation_stride_bits: 264,
        slot_stride_bits: 8,
        y_offset_bits: 88,
        x_offset_bits: 96,
        pair_stride_bits: 16,
    },
    instructions: Some(InstructionLayout {
        base_bit: 896,
        side_stride_bits: 128,
        index_stride_bits: 64,
        part_stride_bits: 32,
    }),
};

/// Where every section sits in the Pes 20 payload.
pub(crate) static PES20: VersionSchema = VersionSchema {
    version: PesVersion::Pes20,
    players: SectionLayout {
        offset: 0x7c,
        count_offset: 0x60,
    },
    player: &PLAYER,
    appearance: None,
    teams: SectionLayout {
        offset: 0x8ed2fc,
        count_offset: 0x64,
    },
    team: &TEAM,
    rosters: SectionLayout {
        offset: 0x9ccc04,
        count_offset: 0x64,
    },
    roster: &ROSTER,
    tactics: SectionLayout {
        offset: 0xa01e3c,
        count_offset: 0x64,
    },
    tactic: &TACTICS,
};

/// Where every section sits in the Pes 21 payload.
pub(crate) static PES21: VersionSchema = VersionSchema {
    version: PesVersion::Pes21,
    players: SectionLayout {
        offset: 0x7c,
        count_offset: 0x60,
    },
    player: &PLAYER,
    appearance: None,
    teams: SectionLayout {
        offset: 0x8ed2fc,
        count_offset: 0x64,
    },
    team: &TEAM_21,
    rosters: SectionLayout {
        offset: 0x9d4648,
        count_offset: 0x64,
    },
    roster: &ROSTER,
    tactics: SectionLayout {
        offset: 0xa09880,
        count_offset: 0x64,
    },
    tactic: &TACTICS,
};
